CREATE TABLE PRODUCTS(
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(100) NOT NULL,
	barcode CHAR(32) NOT NULL,
	status VARCHAR(20) NOT NULL,
	active TINYINT NOT NULL DEFAULT 1,
	quantity INT NOT NULL,
	weight DOUBLE,
	remarks TEXT,
	price_sell DOUBLE NOT NULL,
	color_id INT NOT NULL,
	size_id INT NOT NULL,
	created_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	created_by INT NOT NULL,
	modified_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	modified_by INT NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE SIZES(
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(10) NOT NULL,
	active TINYINT NOT NULL DEFAULT 1,
	created_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	created_by INT NOT NULL,
	modified_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	modified_by INT NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE COLORS(
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(50) NOT NULL,
	active TINYINT NOT NULL DEFAULT 1,
	created_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	created_by INT NOT NULL,
	modified_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	modified_by INT NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE SUPPLIERS(
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(250) NOT NULL,
	email VARCHAR(100) NOT NULL,
	address TEXT NOT NULL,
	address2 TEXT NOT NULL,
	contact VARCHAR(12) NOT NULL,
	contact2 VARCHAR(12) NOT NULL,
	active TINYINT DEFAULT 1,
	created_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	created_by INT NOT NULL,
	modified_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	modified_by INT NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE INVOICES(
	id INT NOT NULL AUTO_INCREMENT,
	date DATETIME NOT NULL,
	number VARCHAR(100) NOT NULL,
	supplier_id INT NOT NULL,
	total_tax DOUBLE NOT NULL,
	remarks TEXT NOT NULL,
	active TINYINT NOT NULL DEFAULT 1,
	created_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	created_by INT NOT NULL,
	modified_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	modified_by INT NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE INVOICES_ITEMS(
	id INT NOT NULL AUTO_INCREMENT,
	invoice_id INT NOT NULL,
	product_id INT NOT NULL,
	quantity INT NOT NULL,
	price DOUBLE NOT NULL,
	status TINYINT NOT NULL,
	remarks TEXT NOT NULL,
	created_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	created_by INT NOT NULL,
	modified_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	modified_by INT NOT NULL,
	PRIMARY KEY (id)
	
);

CREATE TABLE STOCK_OUT (
	id INT NOT NULL AUTO_INCREMENT,
	product_id INT NOT NULL,
	quantity INT NOT NULL,
	remarks TEXT NOT NULL,
	created_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	created_by INT NOT NULL,
	modified_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	modified_by INT NOT NULL,
	PRIMARY KEY (id)
);